dataset:
  fqdn: xd.xview3.vessel_class.dataset.PPV6
  scene_fqdn: xd.xview3.vessel_class.dataset.PPV2ShipCropInferenceDataset
  crop_size: 256
  num_workers: 32
  batch_size: 64

scene_inference:
  dataset: xd.xview3.vessel_length.dataset

train:
  working_basedir: data/working/xview3
  augmentation:
    func: xd.xview3.vessel_class.augmentation.augv7_crop128
    kwargs: {}

  loss:
    fqdn: torch.nn.CrossEntropyLoss
    kwargs: {}

  model:
    fqdn: timm.create_model
    kwargs:
      model_name: resnet50d
      pretrained: true
      num_classes: 3

  total_epochs: 10

  optimizer:
    fqdn: torch.optim.Adam
    kwargs:
      lr: 0.0001 # 1e-4
      weight_decay: 0.00001

  scheduler:
    fqdn: torch.optim.lr_scheduler.CosineAnnealingLR
    kwargs:
      T_max: 1
      eta_min: 0.0000001 # 1e-7
