dataset:
  fqdn: xd.xview3.vessel_length.dataset.PPV2ShipCropTrainValDataset
  scene_fqdn: xd.xview3.vessel_length.dataset.PPV2ShipCropInferenceDataset
  crop_size: 128
  chip_image_size: 800
  length_upper: 200 # 95% point
  length_lower: 15 # 5% point

train:
  working_basedir: data/working/xview3
  augmentation:
    func: xd.xview3.vessel_length.augmentation.get_xview3_augv3
    kwargs: {}

  loss:
    fqdn: torch.nn.MSELoss
    kwargs: {}

  model:
    fqdn: timm.create_model
    kwargs:
      model_name: resnet50
      pretrained: true
      num_classes: 1

  total_epochs: 20

  optimizer:
    fqdn: torch.optim.Adam
    kwargs:
      lr: 0.000005 # 5e-6
      weight_decay: 0.00001

  scheduler:
    fqdn: torch.optim.lr_scheduler.CosineAnnealingLR
    kwargs:
      T_max: 1
      eta_min: 0.00000001 # 1e-8
